### ISSUE TITLE
Stub Library API pages

### ISSUE THREAD

**Issue by JackDunaway** [featherweight/featherweight.github.io#1]
Create `_docs` markdown stubs that specify API namespaces. Within each namespace, all functions will be documented as a single, long scrolling page. Permalinks (and page anchors) to each API method are given for linking.

**Comment by jassems** [comment]
FTW Run-time API
- ftw.actor.connector
- ftw.actor.context
- ftw.actor.instance
- ftw.actor.logger
- ftw.actor.message
- ftw.actor.request
- ftw.actor.router
- ftw.actor.scheduler
- ftw.actor.socket
- ftw.actor.subscription
- ftw.actor.support
- ftw.database.sqlite
- ftw.error
- ftw.file
- ftw.json
- ftw.numeric
- ftw.reflection
- ftw.regex
- ftw.string
- ftw.system
- ftw.time

FTW IDE API & Utilities
- ftw.codegen
- ftw.utils
- ftw.lib

Internal / Prototype / Experimental / Slated for Deprecation
- ftw.application
- ftw.email
- ftw.http.client
- ftw.http.server
- ftw.ui
- ftw.uri
- ftw.viserver
- ftw.windows.file
- ftw.windows.security
- ftw.windows.string
- ftw.windows.transfer
- ftw.windows.xml

Other Pages
- examples
- templates
- tests

**Comment by JackDunaway** [comment]
done: http://featherweight.io
